### ISSUE TITLE
ビーンのインスタンス生成が無駄になっている

### ISSUE THREAD

**Issue by essences** [inotakeshi/nikaime#1]
[SerchSerblet.java](https://github.com/inotakeshi/nikaime/blob/master/src/web/SerchSerblet.java)
４４行目で生成したインスタンスが４８行目で消えている。

この部分がむだなので、インスタンス生成はサービスにまかせましょう。		SerchBean sb=new SerchBean();

**Comment by inotakeshi** [comment]
サービスに任せました
